apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
    spec:
      containers:
      - name: mi-app
        image: nginx:latest
        ports:
        - containerPort: 80
